### PR TITLE
Comply with REUSE 3.0

### PR DESCRIPTION
**Pull request by kirelagin**
* REUSE 3.0 no longer allows `Valid-License-Identifier`
* Add missing licensing information to some files

### CODE REVIEW

**Comment by Lucus16** [comment]
Can the `LICENSE` file be dropped? I prefer to keep the root of the repository clean, I think just the `LICENSES` directory should be enough.

**Comment by kirelagin** [comment]
It can be dropped in the sense that it will not affect REUSE 3.0 compliance, but, unfortunately, this file is used by GitHub to detect the license. If we don’t care about the right license being displayed in the GUI, then ok.

**Comment by Lucus16** [comment]
Ok, sucks, but I guess we'll keep it.

**Comment by Lucus16** [comment]
Patched missing year.

**Pull request merged**
